# Generated by Django 4.2.7 on 2024-04-21 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('projectid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('cdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='todo',
            fields=[
                ('todoid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('status', models.TextField()),
                ('crdate', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.project')),
            ],
        ),
    ]
