# Generated by Django 4.2.7 on 2024-04-21 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='pid',
        ),
        migrations.AddField(
            model_name='project',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.todo'),
        ),
    ]
