# Generated by Django 4.2.7 on 2024-04-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_rename_id_todo_todo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_id',
            new_name='id',
        ),
    ]
